// fundamentals.js
export const fundamentals = [
  { name: "Dividendo anual", key: "annualDividendPerShare" },
  { name: "Valor contábil", key: "bookValue" },
  { name: "Lucro por ação", key: "eps" },
  { name: "Valor de mercado", key: "marketCap" },
  { name: "Valor da empresa", key: "enterpriseValue" },
  { name: "EBITDA", key: "ebitda" },
  { name: "Ações em circulação", key: "floatShares" },
  { name: "Risco geral", key: "overallRisk" },
  { name: "Preço alvo alto", key: "targetHighPrice" },
  { name: "Preço alvo baixo", key: "targetLowPrice" },
  { name: "Preço alvo médio", key: "targetMeanPrice" },
  { name: "Preço alvo mediano", key: "targetMedianPrice" },
  { name: "Dívida total", key: "totalDebt" },
  { name: "Patrimônio líquido", key: "totalEquity" },
  { name: "Caixa", key: "cash" },
  { name: "Receita", key: "revenue" },
  { name: "Lucro líquido", key: "netIncome" },
  { name: "Receita ano anterior", key: "lastYearRevenue" },
  { name: "Máxima 52 semanas", key: "fiftyTwoWeekHigh" },
  { name: "Mínima 52 semanas", key: "fiftyTwoWeekLow" },
  { name: "P/L", key: "priceToEarningsRatio" },
  { name: "Dividend Yield", key: "dividendYield" },
  { name: "Dívida / Patrimônio", key: "debtToEquity" },
  { name: "EV / EBITDA", key: "enterpriseToEbitda" },
  { name: "EV / Receita", key: "enterpriseToRevenue" },
  { name: "P/B", key: "priceToBook" },
  { name: "Payout Ratio", key: "payoutRatio" },
  { name: "ROE", key: "returnOnEquity" },
  { name: "Crescimento da Receita", key: "revenueGrowth" },
  { name: "Receita por ação", key: "revenuePerShare" },
  { name: "Variação máxima 52 semanas", key: "fiftyTwoWeekHighChange" },
  {
    name: "Variação % máxima 52 semanas",
    key: "fiftyTwoWeekHighChangePercent",
  },
  { name: "Variação mínima 52 semanas", key: "fiftyTwoWeekLowChange" },
  { name: "Variação % mínima 52 semanas", key: "fiftyTwoWeekLowChangePercent" },
  { name: "Preço atual", key: "currentPrice" },
];
